### ISSUE TITLE
Reliable P2P file-transfers though webtorrent?

### ISSUE THREAD

**Issue by poVoq** [conversejs/community-plugins#103]
https://github.com/kern/filepizza

Might be possible to use as an ConverseJS addon.

**Comment by licaon-kter** [comment]
That sounds rather odd given that XMPP has file transfers.

**Comment by poVoq** [comment]
no, because http_upload is not the same, and jingle file transfers arn't working very well.

**Comment by licaon-kter** [comment]
So why not fix Jingle then, instead of adding some other node daemon?
