### ISSUE TITLE
SEARCH with 4.2.0 not visible anywhere

### ISSUE THREAD

**Issue by anilk9096** [conversejs/community-plugins#11]
HI,

we integrated search plugin in to our converse application. and can see in console search plugin was ready . but missing search icon . can you guide how to acheive this

**Comment by deleolajide** [comment]
Just updated the demo.html test page to use 4.2.0 and search is working for me

![image](https://user-images.githubusercontent.com/110731/62557455-ee927600-b86e-11e9-8fa5-531ca86a6427.png)

**Comment by anilk9096** [comment]
Thank you it worked for me

**Comment by manasakamireddy** [comment]
@deleolajide  is the search plugin working for u in all the times you are searching?
whats happening for me is some times it was not working .....,even if i  give full matched word also results are not displaying...
