### ISSUE TITLE
Seach plugin requires smilely button, otherwise breaks converseJS

### ISSUE THREAD

**Issue by poVoq** [conversejs/community-plugins#17]
I have  `visible_toolbar_buttons: {emoji: false},` set on my mobile view-mode instance as it is broken on small screens and the OSK comes with it's own smilies, but when I try to enable the search plugin it gives the following error: 
`TypeError: smiley is null  search.js:175:13`

With that it still loads into the control box but I can join any chats or MUCs.

**Comment by poVoq** [comment]
Hmm, seems to be a more general issue as the same happens with the info plugin.

**Comment by deleolajide** [comment]
>the same happens with the all the other plugins that add an icon to the tool-bar.

That code is now very dated. I don't override *renderToolbar* **method** any more. I now listen to to the *renderToolbar* **event**. In any case, it should be easy enough to fix by using the parent element.
