### ISSUE TITLE
Search - should search for type `chat` in 1:1 and `groupchat` in MUCs

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/community-plugins#21]
Converse HEAD (https://github.com/conversejs/converse.js/commit/4aa6b728cf15d8b1cd6dac745c02dd4df3ac1e40), Search plugin HEAD (37aa611d79983a5ee8c7a8e3c86bd5afbc7d2bf0), ejabberd HEAD

Search in MUCs, everything ok (eg. ejabberd MUC)

Search in a 1:1, log says `WARNING: Did not fetch MAM archive for mycontact@mydomain.tld because it doesn't support urn:xmpp:mam:2`

What am I missing?

**Comment by deleolajide** [comment]
Unable to reproduce as I use openfire and not ejabberd

**Comment by weiss** [comment]
ejabberd supports and [announces][1] the `urn:xmpp:mam:2` feature.

[1]: https://xmpp.org/extensions/xep-0313.html#support

**Comment by licaon-kter** [comment]
In https://github.com/conversejs/community-plugins/blob/master/search/search.js#L78 (surely I'm wrong) but why `groupchat` ? Won't 1:1 be not-groupchat?

**Comment by licaon-kter** [comment]
@deleolajide 
> Unable to reproduce as I use openfire

So it finds messages type `groupchat` in 1:1 chats? Why? How?

**Comment by deleolajide** [comment]
Try now with my last commit.

**Comment by licaon-kter** [comment]
Better, thanks.
