### ISSUE TITLE
Search - also search local DB for decrypted messages

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/community-plugins#27]
As seen in https://github.com/conversejs/community-plugins/issues/21 after using type `chat` the plugin works in 1:1, but as the description implies, only for messages from MAM.

MAM messages means _**un**encrypted messages_, while I have on screen plenty of text, the plugin doesn't find anything....that was OMEMO encrypted.

Hope the plugin can be extended to include local DB saved messages too.

**Comment by deleolajide** [comment]
I have a different version that does do that. I will try to merge both into a unified version with a setting to select search mechanism

**Comment by licaon-kter** [comment]
Thanks
