### ISSUE TITLE
Media Content Summary 

### ISSUE THREAD

**Issue by rodrigolzd** [conversejs/community-plugins#3]
This is a desirable feature of Telegram that is needed in Converse.

Converse keeps a record of the different types of user shared content and it shows them in a list. Making much easier to locate what was posted later on. 

If you ever looked for a link you posted on a chat room you'll find this will help you alot.

This could be either a plugin or a feature in converse

![captura de tela 2018-12-20 10 58 50](https://user-images.githubusercontent.com/4949495/50294149-6fc20780-045c-11e9-9a4a-62cf0ac30f6c.png)
![captura de tela 2018-12-20 11 09 01](https://user-images.githubusercontent.com/4949495/50294174-79e40600-045c-11e9-8118-1c00fb74386e.png)

**Comment by deleolajide** [comment]
@jcbrand What do you think? Plugin or core feature?

**Comment by jcbrand** [comment]
I'm not sure what the best way would be to implement such a feature. Ideally it should be possible to query the XMPP server to get such a summary, but I don't think it is.

I'd opt for plugin for now, we can always merge plugins into core later.

**Comment by deleolajide** [comment]
If we assume most media will be added by http hyperlinks (including http uploads), then we can perform a MAM query and scan for MIME type in the chat body to get a summary and the drill-down detail.

**Comment by deleolajide** [comment]
This is now available in Pade version 0.9.0

![image](https://user-images.githubusercontent.com/110731/50715322-ad39ae00-1074-11e9-830a-66ee9839de57.png)

Anyone looking for a first plugin to tackle can look at making it a standalone plugin for Converse.

**Comment by deleolajide** [comment]
Also now available as a standalone plugin called [content-summary](https://github.com/conversejs/community-plugins/blob/master/content-summary/readme.md). See commit https://github.com/conversejs/community-plugins/commit/9ccecd041b74adfb185553ee5534bf34d367d46e
