### ISSUE TITLE
Jitsimeet plugin not working with conversejs v9.0.0

### ISSUE THREAD

**Issue by nikita-cerejo** [conversejs/community-plugins#348]
I already have conversejs v9.0.0 working with core features. But I needed to add jitsimeet for audio and video call purpose so I added jitsimeet.js file just to check if its working.
I am getting video call icon in toolbar buttons but getting error in console. 
Please check below screenshot for more details. And let me know if any more information required.

![jitsimeet model error](https://user-images.githubusercontent.com/90706172/144568364-bd5d1e03-b981-4ad4-a20c-b58e6b5cd80c.PNG)

Can anyone help me with any solution to this issue?
@jcbrand  @deleolajide @SilverYoCha

**Comment by SilverYoCha** [comment]
Hi,

Version 8 https://github.com/conversejs/converse.js/tree/v8.0.0 introduced some breaking changes.
The screenshot shows one of them about event afterMessageBodyTransformed which the signature as changed around parameters.

Other breaking changes get impacts on jitsimeet plugin.

I already applied modifications on my own environment to get the plugin working with 8.0.1 version, but I did not propose yet a PR.
I will soon propose one with jitsimeet plugin directly compatible with version 9 of conversejs.
Next week I hope.

**Comment by deleolajide** [comment]
> I will soon propose one with jitsimeet plugin directly compatible with version 9 of conversejs.

Thanks. If you do that, then I will replace the existing v7.x /dist folder with v9.x and start working on all the other plugins 👍

**Comment by deleolajide** [comment]
Got a free day this week and decided to upgrade all plugins. It is now working for me at https://conversejs.github.io/community-plugins

![image](https://user-images.githubusercontent.com/110731/145081996-4cf18682-eb6d-4526-bc71-f398e9c22b5f.png)

**Comment by SilverYoCha** [comment]
Nice!

I started to modify JitsiMeet plugin with some little changes against new version of ConverseJS.

But I have some troubles to run command 'make node_modules' or 'make serve'. Is there anything I have to do before executing these commands ?

**Comment by deleolajide** [comment]
I build on Windows using WSL2. I use 
```
make dev
```
See https://github.com/conversejs/converse.js/issues/2043#issuecomment-951744713

**Comment by SilverYoCha** [comment]
Thank you for your help.

I finally succeed to get `make serve` working by modifying two things.
I added this into package.json :
```
  "scripts": {
    "bootstrap": "lerna bootstrap --hoist"
  }
```
And I replaced into Makefile `npm run lerna` by `npm run bootstrap`.

Not sure that is a right way, so I did not suggest these modifications into a PR.

**Comment by nikita-cerejo** [comment]
Jitsmimeet is working with v9.0.0  but screenshare option gives error in it.
Below is screenshot of the error from console. Hope it helps to resolve the issue. Please let me know if I missed out any setting which causes this error.

![image](https://user-images.githubusercontent.com/90706172/147070513-26f35b86-77d2-4f31-a5a6-95afa5a0637c.png)

**Comment by deleolajide** [comment]
> but screenshare option gives error in it.

The error says **disallowed by permission policy**. That looks like a user error to me

**Comment by nikita-cerejo** [comment]
When I try the same on `https://meet.jit.si/ ` I get a modal for screen share to select what I want to share like the whole screen or just a window etc. but I don't get this modal in conversejs community jitsimeet plugin. Instead I get that error as mentioned above.

**Comment by deleolajide** [comment]
> Instead I get that error as mentioned above.

Try re-configuring the plugin to open in a browser tab window instead of an an embedded iframe

**Comment by nikita-cerejo** [comment]
Since the plugin is working in v9.0.0, closing this issue. 
Thanks for your support @deleolajide @SilverYoCha
