### ISSUE TITLE
Option to disable PDF button in Search plugin?

### ISSUE THREAD

**Issue by poVoq** [conversejs/community-plugins#37]
In some browsers or platforms the PDF functionality will not work, thus the button is a bit confusing. Would be nice to optionally disable/hide it.

An alternative might be a Print button as that is more widely supported and can also be used to make pdfs.

**Comment by deleolajide** [comment]
> Would be nice to optionally disable/hide it.
Agreed. I will make the change

>An alternative might be a Print button
That is a normal browser function, so no point adding the button.
