### ISSUE TITLE
screencast issue (doesn't load anything)

### ISSUE THREAD

**Issue by roughnecks** [conversejs/community-plugins#513]
Hi,

I'm trying the screencast plugin in my LAN with 2 desktop PCs. Problem is, after I start casting from one PC, nothing loads on the second and vice versa.. So it looks like it's casting from one side (I have the popup window and can select what to cast), but nothing really happens in destination.

**Comment by deleolajide** [comment]
See https://github.com/conversejs/community-plugins/tree/master/packages/screencast

You toggle start/stop with the screen icon. After you stop, it will upload the recoded video file using http file upload. make sure that is enabled otherwise the destination will not receive the video file

**Comment by roughnecks** [comment]
The screen icon always wants me to start casting, even if I press it twice (one to start and the second time to stop, it's not working).

**Comment by roughnecks** [comment]
Found out the issue; if you don't allow the site to use mic, it won't stop the cast and won't upload the file.
