### ISSUE TITLE
screencast: navigator.mediaDevices is undefined

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/community-plugins#6]
Firefox 66

@deleolajide Was this tested only in Chrome?

**Comment by deleolajide** [comment]
Yes. I only use chromium based browsers

**Comment by licaon-kter** [comment]
That's ok given your Pade extension, that's bad given this should work in any browser.

Chrome is the new IE. :(

**Comment by deleolajide** [comment]
> Chrome is the new IE. :(

Notice I said Chromium and not Chrome. It is a double edged sword. I prefer to see that Chromium is the new Linux kernel everyone is working on except Apple and Mozilla.

Having said that, Firefox should support it mediaDevices. See https://developer.mozilla.org/en-US/docs/Web/API/Navigator/mediaDevices

**Comment by deleolajide** [comment]
> That's ok given your Pade extension,

Many chrome extensions run with minimal changes in Firefox. See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension.

I don't see Pade being an exception. I just don't have any motivation to do it. That should be an exercise for someone else who uses Firefox enough to get it done easily.

**Comment by licaon-kter** [comment]
> Notice I said Chromium and not Chrome.

I did, but that doesn't change much.

> Having said that, Firefox should support mediaDevices. 

True, I'll try to find if this is a client setup issue on my side.

> That should be an exercise for someone else who uses Firefox enough to get it done easily.

Hope someone can, if there are still devs that can code for non-Chrom* that is.

**Comment by deleolajide** [comment]
> Hope someone can, if there are still devs that can code for non-Chrom* that is.

Please read the moz liink I posted on chrome extensions. Browser extensions is now a web standard with a browser.xxx namespace and Mozilla have even gone out of their way to support the chrome.xxx namespace making t so easy to port a chrome extension to Firefox. **There is nothing to re-code.**

**Comment by licaon-kter** [comment]
@deleolajide my bad, forgot to add a :) to that sentece  ;)
