### ISSUE TITLE
Search and Content-summary not working with HEAD

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/community-plugins#9]
...but working with 4.2.0

Will try to pinpoint the exact commit.

**Comment by licaon-kter** [comment]
Got it, `git bisect`ed my way to the first commit that broke them: https://github.com/conversejs/converse.js/commit/15b22736315839d46ef51c3b490c1c48f8c507f6

**Comment by deleolajide** [comment]
Thanks for the heads up
I am so not looking forward to fixing all the plugins broken in the next version of Converse

**Comment by licaon-kter** [comment]
@deleolajide In [this picture](https://github.com/conversejs/converse.js/issues/1682#issuecomment-526129327) you have search enabled, so did you fix it for 5.0.x?

**Comment by deleolajide** [comment]
> @deleolajide In [this picture](https://github.com/conversejs/converse.js/issues/1682#issuecomment-526129327) you have search enabled, so did you fix it for 5.0.x?

I guess so. At some point, changes to Pade will upstream back to the community plugin.

**Comment by licaon-kter** [comment]
I'll wait then, thanks

**Comment by licaon-kter** [comment]
Trying HEAD, search appears to work somewhat... not finding all the occurrences of a string but only some.

Content-summary still shows a blank sidebar window in Firefox/Vivaldi, fun fact the console info shows that the plugin actually got the links info ok.

**Comment by deleolajide** [comment]
> Content-summary still shows a blank sidebar window in Firefox/Vivaldi, fun fact the console info shows that the plugin actually got the links info ok.

That would be https://github.com/conversejs/converse.js/issues/1416. I had to hack Converse in Pade to make that work.

**Comment by deleolajide** [comment]
> Trying HEAD, search appears to work somewhat... not finding all the occurrences of a string but only some.

```
var searchRegExp = new RegExp('^(.*)(\s?' + keyword + ')', 'i');
```

That was the regex used. I am not that good with regex. Any improvement on that would be appreciated.
